void __cdecl setupdll_ ( long *, char [ 10000 ], char [ 255 ], char [ 3 ], long *, char [ 255 ], long , long , long , long );
void __cdecl setrefdll_ ( char [ 3 ], long *, double *, double *, double *, double *, double *, long *, char [ 255 ], long , long );
void __cdecl setmixdll_ ( char [ 255 ], char [ 255 ], char [ 3 ], long *, char [ 10000 ], double *, long *, char [ 255 ], long , long , long , long , long );
void __cdecl setmoddll_ ( long *, char [ 3 ], char [ 3 ], char [ 60 ], long *, char [ 255 ], long , long , long , long );
void __cdecl setpathdll_ ( char [ 255 ], long );
void __cdecl gerg04dll_ ( long *, long *, long *, char [ 255 ], long );
void __cdecl setktvdll_ ( long *, long *, char [ 3 ], double *, char [ 255 ], long *, char [ 255 ], long , long , long );
void __cdecl getktvdll_ ( long *, long *, char [ 3 ], double *, char [ 255 ], char [ 255 ], char [ 255 ], char [ 255 ], long , long , long , long , long );
void __cdecl getfijdll_ ( char [ 3 ], double *, char [ 255 ], char [ 255 ], long , long , long );
void __cdecl preosdll_ ( long *);
void __cdecl setagadll_ ( long *, char [ 255 ], long );
void __cdecl unsetagadll_ ();
void __cdecl namedll_ ( long *, char [ 12 ], char [ 80 ], char [ 12 ], long , long , long );
void __cdecl pureflddll_ ( long *);
void __cdecl setncdll_ ( long *);
void __cdecl rpversion_ ( char [ 255 ], long );

void __cdecl critpdll_ ( double *, double *, double *, double *, long *, char [ 255 ], long );

void __cdecl thermdll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *);
void __cdecl therm2dll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *);
void __cdecl therm3dll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *);
void __cdecl therm0dll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *);
void __cdecl pressdll_ ( double *, double *, double *, double *);
void __cdecl enthaldll_ ( double *, double *, double *, double *);
void __cdecl entrodll_ ( double *, double *, double *, double *);
void __cdecl cvcpdll_ ( double *, double *, double *, double *, double *);
void __cdecl gibbsdll_ ( double *, double *, double *, double *, double *);
void __cdecl agdll_ ( double *, double *, double *, double *, double *);
void __cdecl residualdll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *);
void __cdecl cp0dll_ ( double *, double *, double *);

void __cdecl dpdddll_ ( double *, double *, double *, double *);
void __cdecl dpdd2dll_ ( double *, double *, double *, double *);
void __cdecl dpdtdll_ ( double *, double *, double *, double *);
void __cdecl dddpdll_ ( double *, double *, double *, double *);
void __cdecl dddtdll_ ( double *, double *, double *, double *);
void __cdecl dhd1dll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *);
void __cdecl virbdll_ ( double *, double *, double *);
void __cdecl vircdll_ ( double *, double *, double *);
void __cdecl virbadll_ ( double *, double *, double *);
void __cdecl vircadll_ ( double *, double *, double *);
void __cdecl dbdtdll_ ( double *, double *, double *);
void __cdecl b12dll_ ( double *, double *, double *);

void __cdecl fgctydll_ ( double *, double *, double *, double *);
void __cdecl fgcty2dll_ ( double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl fugcofdll_ ( double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl chempotdll_ ( double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl actvydll_ ( double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl excessdll_ ( double *, double *, double *, long *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );

void __cdecl satsplndll_ ( double *, long *, char [ 255 ], long );
void __cdecl sattpdll_ ( double *, double *, double *, long *, long *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl sattdll_ ( double *, double *, long *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl satpdll_ ( double *, double *, long *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl satddll_ ( double *, double *, long *, long *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl sathdll_ ( double *, double *, long *, long *, long *, double *, double *, double *, long *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl satedll_ ( double *, double *, long *, long *, long *, double *, double *, double *, long *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl satsdll_ ( double *, double *, long *, long *, long *, double *, double *, double *, long *, double *, double *, double *, long *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl cv2pkdll_ ( long *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl csatkdll_ ( long *, double *, long *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl dptsatkdll_ ( long *, double *, long *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl psatkdll_ ( long *, double *, double *, long *, char [ 255 ], long );
void __cdecl dlsatkdll_ ( long *, double *, double *, long *, char [ 255 ], long );
void __cdecl dvsatkdll_ ( long *, double *, double *, long *, char [ 255 ], long );

void __cdecl melttdll_ ( double *, double *, double *, long *, char [ 255 ], long );
void __cdecl mlth2odll_ ( double *, double *, double *);
void __cdecl meltpdll_ ( double *, double *, double *, long *, char [ 255 ], long );
void __cdecl subltdll_ ( double *, double *, double *, long *, char [ 255 ], long );
void __cdecl sublpdll_ ( double *, double *, double *, long *, char [ 255 ], long );

void __cdecl tprhodll_ ( double *, double *, double *, long *, long *, double *, long *, char [ 255 ], long );
void __cdecl tpflshdll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl tdflshdll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl pdflshdll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl phflshdll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl psflshdll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl peflshdll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl thflshdll_ ( double *, double *, double *, long *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl tsflshdll_ ( double *, double *, double *, long *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl teflshdll_ ( double *, double *, double *, long *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl dhflshdll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl dsflshdll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl deflshdll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl hsflshdll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl esflshdll_ ( double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl tqflshdll_ ( double *, double *, double *, long *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl pqflshdll_ ( double *, double *, double *, long *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl abfl1dll_ ( double *, double *, double *, long *, char [ 2 ], double *, double *, double *, double *, double *, long *, char [ 255 ], long , long );
void __cdecl abfl2dll_ ( double *, double *, double *, long *, long *, char [ 2 ], double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long , long );
void __cdecl dbfl1dll_ ( double *, double *, double *, char [ 2 ], double *, double *, long *, char [ 255 ], long , long );
void __cdecl dbfl2dll_ ( double *, double *, double *, long *, char [ 2 ], double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long , long );
void __cdecl pdfl1dll_ ( double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl phfl1dll_ ( double *, double *, double *, long *, double *, double *, long *, char [ 255 ], long );
void __cdecl psfl1dll_ ( double *, double *, double *, long *, double *, double *, long *, char [ 255 ], long );

void __cdecl trnprpdll_ ( double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl dielecdll_ ( double *, double *, double *, double *);
void __cdecl surftdll_ ( double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl surtendll_ ( double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl heatdll_ ( double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl CSTARdll ( double *, double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl fpvdll_ ( double *, double *, double *, double *, double *);


void __cdecl wmoldll_ ( double *, double *);
void __cdecl xmassdll_ ( double *, double *, double *);
void __cdecl xmoledll_ ( double *, double *, double *);
void __cdecl qmassdll_ ( double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl qmoledll_ ( double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long );
void __cdecl infodll_ ( long *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *);
void __cdecl limitsdll_ ( char [ 3 ], double *, double *, double *, double *, double *, long );
void __cdecl limitxdll_ ( char [ 3 ], double *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long , long );
void __cdecl limitkdll_ ( char [ 3 ], long *, double *, double *, double *, double *, double *, double *, double *, long *, char [ 255 ], long , long );
