#ifndef REFPROP_TYPES_C_H
#define REFPROP_TYPES_C_H
//
// I'll try to follow this example from:
// http://www.gershnik.com/tips/cpp.asp
// function type: typedef void [compiler stuff]  func_t(int, float);
// function declaration: func_t func;
// pointer type: typedef func_t * func_ptr;
// 
// For C calling conventions, replaced all "double &" with "double *", and "long &" with "long *"
// This has been taken from the Refprop example files by Ian Bell available from NIST
//
// extra function for setup
typedef void (LIBRARY_API RPVersion_TYPE )( char* );
typedef void (LIBRARY_API SETPATHdll_TYPE)( const char* );
//
typedef void (LIBRARY_API ABFL1dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API ABFL2dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API ACTVYdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API AGdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API CCRITdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API CP0dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API CRITPdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API CSATKdll_TYPE)(INTEGER *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API CV2PKdll_TYPE)(INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API CVCPKdll_TYPE)(INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API CVCPdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API DBDTdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API DBFL1dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API DBFL2dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API DDDPdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API DDDTdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API DEFLSHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API DHD1dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API DHFL1dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );//added by henning francke
typedef void (LIBRARY_API DHFL2dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );//added by henning francke
typedef void (LIBRARY_API DHFLSHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API DIELECdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API DOTFILLdll_TYPE)(INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API DPDD2dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API DPDDKdll_TYPE)(INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API DPDDdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API DPDTKdll_TYPE)(INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API DPDTdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API DPTSATKdll_TYPE)(INTEGER *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API DSFLSHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API DSFL1dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );//added by henning francke
typedef void (LIBRARY_API DSFL2dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );//added by henning francke
typedef void (LIBRARY_API ENTHALdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API ENTROdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API ESFLSHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API FGCTYdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API FPVdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API GERG04dll_TYPE)(INTEGER *,INTEGER *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API GETFIJdll_TYPE)(char*,DOUBLE_PRECISION *,char*,char*,INTEGER ,INTEGER ,INTEGER );
typedef void (LIBRARY_API GETKTVdll_TYPE)(INTEGER *,INTEGER *,char*,DOUBLE_PRECISION *,char*,char*,char*,char*,INTEGER ,INTEGER ,INTEGER ,INTEGER ,INTEGER );
typedef void (LIBRARY_API GIBBSdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API HSFLSHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API INFOdll_TYPE)(INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API LIMITKdll_TYPE)(char*,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER ,INTEGER );
typedef void (LIBRARY_API LIMITSdll_TYPE)(char*,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER );
typedef void (LIBRARY_API LIMITXdll_TYPE)(char*,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER ,INTEGER );
typedef void (LIBRARY_API MELTPdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API MELTTdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API MLTH2Odll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API NAMEdll_TYPE)(INTEGER *,char*,char*,char*,INTEGER ,INTEGER ,INTEGER );
typedef void (LIBRARY_API PDFL1dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API PDFLSHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API PEFLSHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API PHFL1dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API PHFLSHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API PQFLSHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API PREOSdll_TYPE)(INTEGER *);
typedef void (LIBRARY_API PRESSdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API PSFL1dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API PSFLSHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API PUREFLDdll_TYPE)(INTEGER *);
typedef void (LIBRARY_API QMASSdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API QMOLEdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API SATDdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API SATEdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,INTEGER *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API SATHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,INTEGER *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API SATPdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API SATSdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,INTEGER *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API SATTdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API SETAGAdll_TYPE)(INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API SETKTVdll_TYPE)(INTEGER *,INTEGER *,char*,DOUBLE_PRECISION *,char*,INTEGER *,char*,INTEGER ,INTEGER ,INTEGER );
typedef void (LIBRARY_API SETMIXdll_TYPE)(char*,char*,char*,INTEGER *,char*,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER ,INTEGER ,INTEGER ,INTEGER ,INTEGER );
typedef void (LIBRARY_API SETMODdll_TYPE)(INTEGER *,char*,char*,char*,INTEGER *,char*,INTEGER ,INTEGER ,INTEGER ,INTEGER );
typedef void (LIBRARY_API SETREFdll_TYPE)(char*,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER ,INTEGER );
//typedef void (LIBRARY_API SETUPdll_TYPE)(INTEGER *,char*,char*,char*,INTEGER *,char*,INTEGER ,INTEGER ,INTEGER ,INTEGER );
typedef void (LIBRARY_API SETUPdll_TYPE)(INTEGER *,char*,char*,char*,INTEGER *,char*);
//  typedef void (LIBRARY_API SPECGRdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *); // not found in library
typedef void (LIBRARY_API SUBLPdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API SUBLTdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API SURFTdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API SURTENdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API TDFLSHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API TEFLSHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API THERM0dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API THERM2dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API THERM3dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API THERMdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API THFLSHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API TPFLSHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API TPFL2dll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );//added by henning francke
typedef void (LIBRARY_API TPRHOdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,INTEGER *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API TQFLSHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API TRNPRPdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API TSFLSHdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *,INTEGER *,char*,INTEGER );
typedef void (LIBRARY_API VIRBdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API VIRCdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API WMOLdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API XMASSdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
typedef void (LIBRARY_API XMOLEdll_TYPE)(DOUBLE_PRECISION *,DOUBLE_PRECISION *,DOUBLE_PRECISION *);
// 
// REFPROP_TYPES_C_H
#endif
