#ifndef REFPROP_TYPES_H
#define REFPROP_TYPES_H
// 
// I'll try to follow this example from:
// http://www.gershnik.com/tips/cpp.asp
// function type: typedef void [compiler stuff]  func_t(int, float);
// function declaration: func_t func;
// pointer type: typedef func_t * func_ptr;
#ifdef __cplusplus
extern "C" {
#endif
  // 
  // Declare the functions for direct access
  RPVersion_TYPE RPVersion;
  SETPATHdll_TYPE SETPATHdll;
  ABFL1dll_TYPE ABFL1dll;
  ABFL2dll_TYPE ABFL2dll;
  ACTVYdll_TYPE ACTVYdll;
  AGdll_TYPE AGdll;
  CCRITdll_TYPE CCRITdll;
  CP0dll_TYPE CP0dll;
  CRITPdll_TYPE CRITPdll;
  CSATKdll_TYPE CSATKdll;
  CV2PKdll_TYPE CV2PKdll;
  CVCPKdll_TYPE CVCPKdll;
  CVCPdll_TYPE CVCPdll;
  DBDTdll_TYPE DBDTdll;
  DBFL1dll_TYPE DBFL1dll;
  DBFL2dll_TYPE DBFL2dll;
  DDDPdll_TYPE DDDPdll;
  DDDTdll_TYPE DDDTdll;
  DEFLSHdll_TYPE DEFLSHdll;
  DHD1dll_TYPE DHD1dll;
  DHFLSHdll_TYPE DHFLSHdll;
  DHFL1dll_TYPE DHFL1dll;
  DHFL2dll_TYPE DHFL2dll;
  DIELECdll_TYPE DIELECdll;
  DOTFILLdll_TYPE DOTFILLdll;
  DPDD2dll_TYPE DPDD2dll;
  DPDDKdll_TYPE DPDDKdll;
  DPDDdll_TYPE DPDDdll;
  DPDTKdll_TYPE DPDTKdll;
  DPDTdll_TYPE DPDTdll;
  DPTSATKdll_TYPE DPTSATKdll;
  DSFLSHdll_TYPE DSFLSHdll;
  DSFL1dll_TYPE DSFL1dll;
  DSFL2dll_TYPE DSFL2dll;
  ENTHALdll_TYPE ENTHALdll;
  ENTROdll_TYPE ENTROdll;
  ESFLSHdll_TYPE ESFLSHdll;
  FGCTYdll_TYPE FGCTYdll;
  FPVdll_TYPE FPVdll;
  GERG04dll_TYPE GERG04dll;
  GETFIJdll_TYPE GETFIJdll;
  GETKTVdll_TYPE GETKTVdll;
  GIBBSdll_TYPE GIBBSdll;
  HSFLSHdll_TYPE HSFLSHdll;
  INFOdll_TYPE INFOdll;
  LIMITKdll_TYPE LIMITKdll;
  LIMITSdll_TYPE LIMITSdll;
  LIMITXdll_TYPE LIMITXdll;
  MELTPdll_TYPE MELTPdll;
  MELTTdll_TYPE MELTTdll;
  MLTH2Odll_TYPE MLTH2Odll;
  NAMEdll_TYPE NAMEdll;
  PDFL1dll_TYPE PDFL1dll;
  PDFLSHdll_TYPE PDFLSHdll;
  PEFLSHdll_TYPE PEFLSHdll;
  PHFL1dll_TYPE PHFL1dll;
  PHFLSHdll_TYPE PHFLSHdll;
  PQFLSHdll_TYPE PQFLSHdll;
  PREOSdll_TYPE PREOSdll;
  PRESSdll_TYPE PRESSdll;
  PSFL1dll_TYPE PSFL1dll;
  PSFLSHdll_TYPE PSFLSHdll;
  PUREFLDdll_TYPE PUREFLDdll;
  QMASSdll_TYPE QMASSdll;
  QMOLEdll_TYPE QMOLEdll;
  SATDdll_TYPE SATDdll;
  SATEdll_TYPE SATEdll;
  SATHdll_TYPE SATHdll;
  SATPdll_TYPE SATPdll;
  SATSdll_TYPE SATSdll;
  SATTdll_TYPE SATTdll;
  SETAGAdll_TYPE SETAGAdll;
  SETKTVdll_TYPE SETKTVdll;
  SETMIXdll_TYPE SETMIXdll;
  SETMODdll_TYPE SETMODdll;
  SETREFdll_TYPE SETREFdll;
  SETUPdll_TYPE SETUPdll;
//  SPECGRdll_TYPE SPECGRdll; // not found in library
  SUBLPdll_TYPE SUBLPdll;
  SUBLTdll_TYPE SUBLTdll;
  SURFTdll_TYPE SURFTdll;
  SURTENdll_TYPE SURTENdll;
  TDFLSHdll_TYPE TDFLSHdll;
  TEFLSHdll_TYPE TEFLSHdll;
  THERM0dll_TYPE THERM0dll;
  THERM2dll_TYPE THERM2dll;
  THERM3dll_TYPE THERM3dll;
  THERMdll_TYPE THERMdll;
  THFLSHdll_TYPE THFLSHdll;
  TPFLSHdll_TYPE TPFLSHdll;
  TPFL2dll_TYPE TPFL2dll;
  TPRHOdll_TYPE TPRHOdll;
  TQFLSHdll_TYPE TQFLSHdll;
  TRNPRPdll_TYPE TRNPRPdll;
  TSFLSHdll_TYPE TSFLSHdll;
  VIRBdll_TYPE VIRBdll;
  VIRCdll_TYPE VIRCdll;
  WMOLdll_TYPE WMOLdll;
  XMASSdll_TYPE XMASSdll;
  XMOLEdll_TYPE XMOLEdll;
  // 
  // Define explicit function pointers
  typedef RPVersion_TYPE * RPVersion_POINTER;
  typedef SETPATHdll_TYPE * SETPATHdll_POINTER;
  typedef ABFL1dll_TYPE * ABFL1dll_POINTER;
  typedef ABFL2dll_TYPE * ABFL2dll_POINTER;
  typedef ACTVYdll_TYPE * ACTVYdll_POINTER;
  typedef AGdll_TYPE * AGdll_POINTER;
  typedef CCRITdll_TYPE * CCRITdll_POINTER;
  typedef CP0dll_TYPE * CP0dll_POINTER;
  typedef CRITPdll_TYPE * CRITPdll_POINTER;
  typedef CSATKdll_TYPE * CSATKdll_POINTER;
  typedef CV2PKdll_TYPE * CV2PKdll_POINTER;
  typedef CVCPKdll_TYPE * CVCPKdll_POINTER;
  typedef CVCPdll_TYPE * CVCPdll_POINTER;
  typedef DBDTdll_TYPE * DBDTdll_POINTER;
  typedef DBFL1dll_TYPE * DBFL1dll_POINTER;
  typedef DBFL2dll_TYPE * DBFL2dll_POINTER;
  typedef DDDPdll_TYPE * DDDPdll_POINTER;
  typedef DDDTdll_TYPE * DDDTdll_POINTER;
  typedef DEFLSHdll_TYPE * DEFLSHdll_POINTER;
  typedef DHD1dll_TYPE * DHD1dll_POINTER;
  typedef DHFLSHdll_TYPE * DHFLSHdll_POINTER;
  typedef DHFL1dll_TYPE * DHFL1dll_POINTER;
  typedef DHFL2dll_TYPE * DHFL2dll_POINTER;
  typedef DIELECdll_TYPE * DIELECdll_POINTER;
  typedef DOTFILLdll_TYPE * DOTFILLdll_POINTER;
  typedef DPDD2dll_TYPE * DPDD2dll_POINTER;
  typedef DPDDKdll_TYPE * DPDDKdll_POINTER;
  typedef DPDDdll_TYPE * DPDDdll_POINTER;
  typedef DPDTKdll_TYPE * DPDTKdll_POINTER;
  typedef DPDTdll_TYPE * DPDTdll_POINTER;
  typedef DPTSATKdll_TYPE * DPTSATKdll_POINTER;
  typedef DSFLSHdll_TYPE * DSFLSHdll_POINTER;
  typedef DSFL1dll_TYPE * DSFL1dll_POINTER;
  typedef DSFL2dll_TYPE * DSFL2dll_POINTER;
  typedef ENTHALdll_TYPE * ENTHALdll_POINTER;
  typedef ENTROdll_TYPE * ENTROdll_POINTER;
  typedef ESFLSHdll_TYPE * ESFLSHdll_POINTER;
  typedef FGCTYdll_TYPE * FGCTYdll_POINTER;
  typedef FPVdll_TYPE * FPVdll_POINTER;
  typedef GERG04dll_TYPE * GERG04dll_POINTER;
  typedef GETFIJdll_TYPE * GETFIJdll_POINTER;
  typedef GETKTVdll_TYPE * GETKTVdll_POINTER;
  typedef GIBBSdll_TYPE * GIBBSdll_POINTER;
  typedef HSFLSHdll_TYPE * HSFLSHdll_POINTER;
  typedef INFOdll_TYPE * INFOdll_POINTER;
  typedef LIMITKdll_TYPE * LIMITKdll_POINTER;
  typedef LIMITSdll_TYPE * LIMITSdll_POINTER;
  typedef LIMITXdll_TYPE * LIMITXdll_POINTER;
  typedef MELTPdll_TYPE * MELTPdll_POINTER;
  typedef MELTTdll_TYPE * MELTTdll_POINTER;
  typedef MLTH2Odll_TYPE * MLTH2Odll_POINTER;
  typedef NAMEdll_TYPE * NAMEdll_POINTER;
  typedef PDFL1dll_TYPE * PDFL1dll_POINTER;
  typedef PDFLSHdll_TYPE * PDFLSHdll_POINTER;
  typedef PEFLSHdll_TYPE * PEFLSHdll_POINTER;
  typedef PHFL1dll_TYPE * PHFL1dll_POINTER;
  typedef PHFLSHdll_TYPE * PHFLSHdll_POINTER;
  typedef PQFLSHdll_TYPE * PQFLSHdll_POINTER;
  typedef PREOSdll_TYPE * PREOSdll_POINTER;
  typedef PRESSdll_TYPE * PRESSdll_POINTER;
  typedef PSFL1dll_TYPE * PSFL1dll_POINTER;
  typedef PSFLSHdll_TYPE * PSFLSHdll_POINTER;
  typedef PUREFLDdll_TYPE * PUREFLDdll_POINTER;
  typedef QMASSdll_TYPE * QMASSdll_POINTER;
  typedef QMOLEdll_TYPE * QMOLEdll_POINTER;
  typedef SATDdll_TYPE * SATDdll_POINTER;
  typedef SATEdll_TYPE * SATEdll_POINTER;
  typedef SATHdll_TYPE * SATHdll_POINTER;
  typedef SATPdll_TYPE * SATPdll_POINTER;
  typedef SATSdll_TYPE * SATSdll_POINTER;
  typedef SATTdll_TYPE * SATTdll_POINTER;
  typedef SETAGAdll_TYPE * SETAGAdll_POINTER;
  typedef SETKTVdll_TYPE * SETKTVdll_POINTER;
  typedef SETMIXdll_TYPE * SETMIXdll_POINTER;
  typedef SETMODdll_TYPE * SETMODdll_POINTER;
  typedef SETREFdll_TYPE * SETREFdll_POINTER;
  typedef SETUPdll_TYPE * SETUPdll_POINTER;
//  typedef SPECGRdll_TYPE * SPECGRdll_POINTER; // not found in library
  typedef SUBLPdll_TYPE * SUBLPdll_POINTER;
  typedef SUBLTdll_TYPE * SUBLTdll_POINTER;
  typedef SURFTdll_TYPE * SURFTdll_POINTER;
  typedef SURTENdll_TYPE * SURTENdll_POINTER;
  typedef TDFLSHdll_TYPE * TDFLSHdll_POINTER;
  typedef TEFLSHdll_TYPE * TEFLSHdll_POINTER;
  typedef THERM0dll_TYPE * THERM0dll_POINTER;
  typedef THERM2dll_TYPE * THERM2dll_POINTER;
  typedef THERM3dll_TYPE * THERM3dll_POINTER;
  typedef THERMdll_TYPE * THERMdll_POINTER;
  typedef THFLSHdll_TYPE * THFLSHdll_POINTER;
  typedef TPFLSHdll_TYPE * TPFLSHdll_POINTER;
  typedef TPFL2dll_TYPE * TPFL2dll_POINTER;
  typedef TPRHOdll_TYPE * TPRHOdll_POINTER;
  typedef TQFLSHdll_TYPE * TQFLSHdll_POINTER;
  typedef TRNPRPdll_TYPE * TRNPRPdll_POINTER;
  typedef TSFLSHdll_TYPE * TSFLSHdll_POINTER;
  typedef VIRBdll_TYPE * VIRBdll_POINTER;
  typedef VIRCdll_TYPE * VIRCdll_POINTER;
  typedef WMOLdll_TYPE * WMOLdll_POINTER;
  typedef XMASSdll_TYPE * XMASSdll_POINTER;
  typedef XMOLEdll_TYPE * XMOLEdll_POINTER;
#ifdef __cplusplus
} // extern "C"
#endif
// REFPROP_TYPES_H
#endif
